	##	https://github.com/flaviofaraon/RehacktorPhp.git
	##	git@github.com:flaviofaraon/RehacktorPhp.git
	##	comando:		make -f Makefile.win

dev:

	@echo "start Dev enviroment"
	@cd frontend && npm start &
	@cd backend && php artisan serve